### ISSUE TITLE
Зачем эта проверка?

### ISSUE THREAD

**Issue by coursar** [evgeniychernyshev/ozon-hw#1]
https://github.com/evgeniychernyshev/ozon-hw/blob/f566d91ad154c0142aba44329bb34de2585efdb8/app/lib.py#L35

**Comment by evgeniychernyshev** [comment]
Чтобы убедиться, что теги добавлены к книге

**Comment by coursar** [comment]
А почему тогда остальные поля так не проверяете?

**Comment by evgeniychernyshev** [comment]
Логично, уберу.
